# Generated by Django 4.0.2 on 2022-02-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='subject',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='auth',
            new_name='author',
        ),
    ]
